### ISSUE TITLE
Use native Firefox settings instead of strange custom setup

### ISSUE THREAD

**Issue by wolftune** [codebicycle/videospeed#10]
I'm not sure what's going on, but the only way to access the settings is via right-clicking the icon in the toolbar. There's no "settings" button accessible via the normal about:addons view.

Perhaps related, I tried to change the settings to match the VLC and mpv keybindings and my changes didn't persist.

**Comment by codebicycle** [comment]
Thanks for your feedback.

I made the modification and I'm testing it now.
The `Preferences` button will be available on the next release.

As for the shortcuts not persisting, I can't reproduce the issue on my end.
Change the shortcuts, click the `Save` button and the changes should persist.

**Comment by wolftune** [comment]
The reason I thought it might be connected: I made the changes and then I removed the icon from the toolbar, then I realized I could no longer access the settings. When I put the icon back, then the settings reset.
