### ISSUE TITLE
Audio cuts out once speed passes 4.00

### ISSUE THREAD

**Issue by JudgementTimeSPD** [codebicycle/videospeed#100]
Just as it says in the title. If I try to push the speed anywhere past 4.00, the audio goes silent no matter what. Not sure if this is an issue with how Firefox plays HTML5 videos, but this issue isn't present in the Chrome version of this app.

**Comment by netjeff** [comment]
It is Firefox that silences audio at 4x and beyond, see #83.

**Comment by codebicycle** [comment]
Unfortunately, Firefox mutes audio when the playback speed is lower than 0.25x or higher than 4x.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate

**Comment by braham-snyder** [comment]
To anyone subbed: if this affects you, you might want to vote on this [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1630569) @sirati filed. You can vote using your GitHub account.
