### ISSUE TITLE
Feature Suggestion: Disable for this Website shortcut

### ISSUE THREAD

**Issue by Kraechtshammer** [codebicycle/videospeed#107]
Hi,
I'd love to have a shortcut to add/remove the current website/domain to the disabled list, in the addon dropdown menu just like in Adblockers etc. This would make it much faster to disable it for sites where it collides with other site controls.

**Comment by codebicycle** [comment]
Hi and thanks for your interest.

This extension is a fork of the `Video Speed Controller` Chrome extension, with minor changes to make it work on Firefox.
It will stay as close as possible to the original https://github.com/igrigorik/videospeed

Any new features should be discussed there, and if implemented they will be available in Firefox too.
