### ISSUE TITLE
consider switching to the mpv/VLC keybindings as default

### ISSUE THREAD

**Issue by wolftune** [codebicycle/videospeed#11]
specifically, LEFT-arrow and RIGHT-arrow for rewind/fast-forward, and [ and ] for slow-down/speed-up.

See https://mpv.io/manual/stable/

These are more logical besides being universal.

**Comment by codebicycle** [comment]
This extension is a fork of the Video Speed Controller Chrome extension, with minor changes to make it work on Firefox.
It will stay as close as possible to the original https://github.com/igrigorik/videospeed

Any new features should be discussed there, and if implemented they will be available in Firefox too.
