### ISSUE TITLE
Feature request: Option to disable extension on current site in the extension menu

### ISSUE THREAD

**Issue by a-macc** [codebicycle/videospeed#110]
It would be great to have an option in the extension menu where one could disable the extension on current site, similar to uBlock Origin which allows to disable the extension only on current site. Presently, disabling the extension on a site requires one to open the extension settings and add the site to the 'Sites on which extension is disabled' field.

**Comment by codebicycle** [comment]
Hi and thanks for your interest.

This extension is a fork of the `Video Speed Controller` Chrome extension, with minor changes to make it work on Firefox.
It will stay as close as possible to the original https://github.com/igrigorik/videospeed

Any new features should be discussed there, and if implemented they will be available in Firefox too.
