### ISSUE TITLE
let arrow keys be used in settings

### ISSUE THREAD

**Issue by wolftune** [codebicycle/videospeed#12]
The settings dialog won't let me enter arrow keys as the keybindings for anything.

**Comment by codebicycle** [comment]
Youtube uses the arrow keys to rewind/fast-forward videos by 5 seconds. J and L keys do it by 10 seconds. ([Youtube shortcuts](https://sites.google.com/a/umich.edu/going-google/accessibility/google-keyboard-shortcuts---youtube))

Allowing arrow keys in the extension will give inconsistent results.
The way the add-on is implemented today if the same shortcut key is implemented in the add-on and on the host site the effects are added together. For example pressing the right arrow key on Youtube will advance the video by 10 seconds (extension default) plus another 5 seconds (Youtube shortcut). 
Other sites use different values.

This add-on is based on a Chrome extension https://github.com/igrigorik/videospeed
Changes that are not Firefox related should be discussed there, and if implemented will be available in Firefox too.
