### ISSUE TITLE
Bad default placement of controlls after update

### ISSUE THREAD

**Issue by Pawloland** [codebicycle/videospeed#120]
After update to latest version on Firefox there are always some issues with placement of controlls. On YouTube they are closer to middle rather than top left (how it was before update). 

![obraz](https://user-images.githubusercontent.com/59684145/107125608-4a4a1f00-68ab-11eb-9edc-701774ed26d8.png)

On Reedit and Facebook they aren't shown at all but controlling through shortcuts works, so it seems that the controlls are overflowing from video frame. For now I am downgrading to older version until it will be fixed.

**Comment by codebicycle** [comment]
Thanks for the feedback.
I've deployed a quick fix.

**Comment by MartinVanIJcken** [comment]
![image](https://user-images.githubusercontent.com/32981209/107142160-3d6e0f80-692d-11eb-8191-e47cac3decbb.png)
I'm not sure if the quick fix solved it. On edx, the controls are now right over the progress bar.

This is on Firefox 85.0.1, on a windows 10 machine.
