### ISSUE TITLE
Please use square-sized button instead of rounded/circle

### ISSUE THREAD

**Issue by kokizzu** [codebicycle/videospeed#121]
previous rounded square is better (easier to click) than circle, now it's annoyingly too small..

**Comment by shortN0te** [comment]
I agree to that. Additional imho a round floating box does not really fit into  a rectangular video player. 
I would not mind to have the choice between multiple designs but adding an Option (maybe simple dropdown menu) for that would be the a good way to please everyone.

**Comment by codebicycle** [comment]
Reverted to the old design with rounded-square buttons.

**Comment by krasnovpro** [comment]
I like the round buttons better. How do I get them back?
