### ISSUE TITLE
add a shortcut to go back to the beginning of video

### ISSUE THREAD

**Issue by kethoven** [codebicycle/videospeed#122]

**Comment by Kraechtshammer** [comment]
In many video players, you can jump to a certain percentage (in steps of 10%) of the video my pressing the number keys 0-9. So if you press 0, you would end up at the beginning. Maybe this helps.

**Comment by codebicycle** [comment]
Hi and thanks for your interest.

This extension is a fork of the `Video Speed Controller` Chrome extension, with minor changes to make it work on Firefox.
It will stay as close as possible to the original https://github.com/igrigorik/videospeed

Any new features should be discussed there, and if implemented they will be available in Firefox too.
