### ISSUE TITLE
Clicking advance or rewind minimizes the controller.

### ISSUE THREAD

**Issue by MartinVanIJcken** [codebicycle/videospeed#123]
Whenever I click on the >> or << buttons in the controler, the controler minimizes and I have to move the cursor to hover over the speed again, which reopens the controller menu, after which I can click a second time (this does not happen when changing the speed). This is rather frustating when attempting to advance quickly by repeatedly pressing advance or rewind.

**Comment by codebicycle** [comment]
Can't reproduce on my end.
Please offer more context.
