### ISSUE TITLE
Feature Suggestion: higher video speed increases time skipped with arrow keys

### ISSUE THREAD

**Issue by Kraechtshammer** [codebicycle/videospeed#126]
I'm currently rewatching a lecture for Uni where I need a higher video speed so I don't fall asleep. I do also use this extension to highly speed up the video so I can kind of skip through the video without missing anything. 
Now I think it would be nice if we were able to set a multiplier that changes the amount of seconds that the arrow keys (advance, rewind) skip, depending on the current video speed. 

Why? 
When I'm watching at speed 1.0, it skips 10 seconds of watch time. When I'm watching at speed 4.0 however, it only skips 2.5s of actual time I would have watched, which is not exactly useful. Now if I was able to, say, multiply the skipped time with my watch speed, I would always skip actual 10 seconds, so this would be very useful to be able to turn on imo.

Any opinions?

**Comment by pbarney** [comment]
This is a fork of a chrome addon that sticks close to the original. Perhaps post this suggestion over on their main project page: https://github.com/igrigorik/videospeed
