### ISSUE TITLE
Feature Request / QOL Improvement : disable setting playback speed to 0

### ISSUE THREAD

**Issue by erus** [codebicycle/videospeed#129]
I've spent 15 minutes trying to understand why videos had stopped playing : my playback speed was set to 0... 
Unless I'm missing something, I can't think of a good reason why someone would want to set the speed to be 0. 
It might be a good improvement to block the possibility of setting the playback speed AT 0.

**Comment by codebicycle** [comment]
Hi and sorry for the inconvenience,

This extension is a fork of the `Video Speed Controller` Chrome extension, with minor changes to make it work on Firefox.
It will stay as close as possible to the original https://github.com/igrigorik/videospeed

Any new features should be discussed there, and if implemented they will be available in Firefox too.
