### ISSUE TITLE
Improve visibility/contrast

### ISSUE THREAD

**Issue by FedericoCeratto** [codebicycle/videospeed#130]
Thanks for developing the extension.
On videos with a dark background it's very difficult to read the current playback speed.
Would you consider adding an outline to the font in use (e.g. black font with white outline)? Thanks

Outline example: https://jsfiddle.net/Kyle_/ZnfED/1/

**Comment by codebicycle** [comment]
Hi and thanks for your interest.

This extension is a fork of the `Video Speed Controller` Chrome extension, with minor changes to make it work on Firefox.
It will stay as close as possible to the original https://github.com/igrigorik/videospeed

Any new features should be discussed there, and if implemented they will be available in Firefox too.
