### ISSUE TITLE
Audio stops at 4x speed or higher

### ISSUE THREAD

**Issue by GrievingVCRs** [codebicycle/videospeed#132]

**Comment by codebicycle** [comment]
Unfortunately, Firefox mutes audio when the playback speed is lower than 0.25x or higher than 4x.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate

**Comment by braham-snyder** [comment]
To anyone subbed: if this affects you, you might want to vote on this [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1630569) @sirati filed. You can vote using your GitHub account.

**Comment by jtagcat** [comment]
@braham-snyder might want to link [vote](https://bugzilla.mozilla.org/page.cgi?id=voting/user.html&bug_id=1630569#vote_1630569), or at least detail, that the vote button is hidden under 'Details'.
