### ISSUE TITLE
The window showing me the speed is gone

### ISSUE THREAD

**Issue by BetrBarker** [codebicycle/videospeed#137]
I know the button, I haven't clicked on it.
I know the check mark, I haven't checked it.
Please fix this, if you already have a way, please tell me.

**Comment by gl1000007** [comment]
Duplicate? #136

**Comment by ykt28403** [comment]
I have the same issue. I use the Video Speed Controller extension every day and absolutely love it. However, it's very frustrating to not be able to see the speed ("controller") anymore. I hit "V" to show/hide the controller, but nothing happens. I typically use Firefox; it sometimes shows up in Chrome, but not always. Any solutions?

**Comment by bunnyhugger22** [comment]
I'm having this issue as well in Firefox. The keyboard shortcuts still work but the window displaying the speed no longer appears.

**Comment by benalt613** [comment]
I have the same issue in Firefox. It sometimes appears. Almost never does in Private mode. Even though I can still speed things up, I cannot see the speed in the box that usually appears in the upper left.

**Comment by ykt28403** [comment]
Yeah. Was there a recent update to the Video Speed Controller extension?

**Comment by deadpahn** [comment]
Yeah same thing for me. Firefox. When I disable and enable and refresh sometimes it comes back but not normally.

**Comment by MavIsBack** [comment]
So, I've just run into the same disappearing-speed-control problem.  I signed up for GitHub in the hopes that I'd see an answer on this thread if I were a subscriber.  Do any more experienced Gits have a clue when we might expect a solution to our problem?

**Comment by aahnik** [comment]
I thought something wrong with my browser. Uninstalled the extension and reinstalled it. Uninstalled the browser and reinstalled it.
Tried changing opacity, Tried hitting 'V'

I am relieved to see this issue. (actually damn frustrated with this problem.)

anyone please solve it. 😥 😭

```shell
❯ firefox --version
Mozilla Firefox 87.0
```

---------

~Update: (on Apr 06 , 2021)~

~its working !!  i think the issue is fixed.~

------

Update: (On Apr 07, 2021)

not working (I don't know why)

------

**Comment by ykt28403** [comment]
Now, YouTube videos won't play in Firefox unless I disable the Video Speed Controller add on.

Is there anyone from codebicycle monitoring this thread? Any ideas?

**Comment by codebicycle** [comment]
The new version 0.6.3.3 should fix the controller not showing in Firefox 87.0

**Comment by gl1000007** [comment]
YES!!!!! 0.6.3.3 WORKS on Firefox 87.0, WIN10 64bit.
Tried it on YouTube and Netflix.
Thanks @codebicycle
