### ISSUE TITLE
Can't use at Bilibili

### ISSUE THREAD

**Issue by Sugarcheng** [codebicycle/videospeed#139]
no button,i changed more time but no effective.

**Comment by AAAlbus** [comment]
Me too

**Comment by codebicycle** [comment]
Hi, the keyboard shortcuts work:

`S` - decrease playback speed
`D` - increase playback speed
`Z` - rewind video by 10 seconds
`X` - advance video by 10 seconds
`R` - reset playback speed to 1.0x
`G` - toggle between current and user-configurable preferred speed
`V` - show/hide the controller

For the interface buttons, there is this ticket upstream https://github.com/igrigorik/videospeed/issues/714
