### ISSUE TITLE
Sync preferences

### ISSUE THREAD

**Issue by katzelad** [codebicycle/videospeed#14]
Great extension!
Would you consider using storage.sync instead of storage.local to sync the preferences?
Thanks

**Comment by codebicycle** [comment]
Check out the new version.
It should be possible to sync preferences between different profiles.

**Comment by codebicycle** [comment]
Version 0.4.9.2 uses storage.sync.

The version after that reverts back to storage.local because storage.sync is not enabled by default in older versions of Firefox.

**Comment by codebicycle** [comment]
The latest versions use storage.sync to synchronize preferences.
