### ISSUE TITLE
Audio choppy on firefox.

### ISSUE THREAD

**Issue by peacealien** [codebicycle/videospeed#146]
I tried moving from chrome to firefox, when I speed up videos in chrome audio is fine, but in firefox the audio becomes choppy. It could be due to video loading slowly, when I pause the video the audio is fine for a bit.

**Comment by hvitoi** [comment]
I face the same problem. 
While watching videos on udemy with playback speeds above 1.5x I get a choppy audio.
While watching videos on youtube with playback speeds below 4x there are no issues at all. Above 4x audio becomes mute.

Both scenarios on Chrome/Chromium run ok. 
Not sure if it's an issue with this extension or firefox itself. This [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1383363) seems related.

**Comment by scottofletcher** [comment]
Also getting this problem. Audio and video choppy on Prime Video on Firefox. runs fine on Chrome.

**Comment by Camusensei** [comment]
This is not a bug from the extension which only tells Firefox to speed up the video.
If you have audio issues on sped up videos in Firefox, open a bug against Firefox. And they'll probably tell you that either your audio driver is too old or your CPU cannot handle the additional processing needed to speed up audio without pitch distortion.
==> Should be closed
