### ISSUE TITLE
Doesn't work since update to v 0.4.9.2

### ISSUE THREAD

**Issue by xhoy** [codebicycle/videospeed#15]
Hi i am using Firefox ESR 52.4.0 ESR on debian linux x64.

Since the update to 0.4.9.2 it doesn't work on youtube and other websites anymore. When i download the old version on https://addons.mozilla.org/en-US/firefox/addon/videospeed/versions/ (0.4.9.1 it works great!)

With kinds regards

**Comment by codebicycle** [comment]
Thanks for reporting this.

The new version allows users to sync preferences between profiles.
In Firefox 52 this option sits behind a flag that you need to turn on in `about:config`.

You can try to update Firefox or go to `about:config` and modify `webextensions.storage.sync.enabled` and set it to `true`.

source:
https://wiki.mozilla.org/WebExtensions/chrome.storage.sync

**Comment by xhoy** [comment]
It also doesn't work on windows 10 with ERS 52.3.0 on Windows.

And yes the flag does enable the function again! Maybe this could be default for ESR?

**Comment by codebicycle** [comment]
Version 0.4.9.2 uses storage.sync, but the version after that reverts back to storage.local.

Sorry for the inconvenience.

**Comment by xhoy** [comment]
Seems to be working with version 4.9.4 ! Thanks
