### ISSUE TITLE
FEATURE REQUEST: Adding a volume boost feature

### ISSUE THREAD

**Issue by CurtisDS** [codebicycle/videospeed#150]
FEATURE REQUEST

I have found other plugins that offer a volume boost of 600% for videos that are just too quiet even at normal max volume. However they clash with this plug in and force the video to play back at 1x speed. It would be nice if this feature could be added to the video speed plug in so that both operations can be used at the same time.

**Comment by jtagcat** [comment]
This seems out of scope for this project.

**Comment by CurtisDS** [comment]
> 
> 
> This seems out of scope for this project.

ya... and its out of scope for the audio booster add on to implement speed controls. So what am I gonna do?

**Comment by jtagcat** [comment]
Use both.

**Comment by codebicycle** [comment]
Unfortunately, this is out of the scope of this extension.
