### ISSUE TITLE
Feature Request - Seek To Time

### ISSUE THREAD

**Issue by DrBlueface** [codebicycle/videospeed#152]
Can there please be a seek to time option thanks a lot for the amazing software

Thanks, Charlie

**Comment by codebicycle** [comment]
Hi and thanks for your interest.

This extension is a fork of the `Video Speed Controller` Chrome extension, with minor changes to make it work on Firefox.
It will stay as close as possible to the original https://github.com/igrigorik/videospeed

Any new features should be discussed there, and if implemented they will be available in Firefox too.
