### ISSUE TITLE
Causes onload window.location to fail to change url on FF Quantum 57

### ISSUE THREAD

**Issue by george-viaud** [codebicycle/videospeed#16]
I'm not sure why, but when I have this plugin enabled, onload seems to fail, or at least in my scenario.

I've setup this test page that exhibits the problem - note that the page should forward to a GNU article.  In my scenario it never does when the plugin is enabled and always does when it is disabled:

http://infinitycyberworks.com/onloadtest.html

**Comment by codebicycle** [comment]
Interesting find!

The extension assigns a function to window.onload.

Adding the following code to your test page, right before the closing body tag, with the extension disabled, should have the same effect, no page redirect.

    <script type="text/javascript">
      window.onload = () => console.log('no-redirect');
    </script>

I'll look more into it.

**Comment by george-viaud** [comment]
Thanks!
Perhaps instead of assigning a function to onload, try appending it?

**Comment by codebicycle** [comment]
I replaced window.onload assignment with an event listener.

You can temporarily load the version from github and test it out.

- Clone this repository.
- Disable the previous version of the extension from Firefox.
  Go to `about:addons` and disable Video Speed Controller.
- Go to `about:debugging` and click Load Temporary Add-on.

The add-on is only loaded temporarily; once you restart your browser, the add-on will no longer be loaded, and you’ll have to re-load it.

**Comment by george-viaud** [comment]
That appears to fix it!  Will this likely make it into production?

**Comment by codebicycle** [comment]
The fix is live now.

**Comment by george-viaud** [comment]
Working - great! Many thanks

**Comment by Undoundoundo** [comment]
Looks like this has regressed in the latest version - inject.js:314

Edit: Aside.. disabling VSC through its own settings did not resolve this issue.. looks like that's because the check to see if VSC is enabled is within the initializeNow() function (called from the window.onload event).  Would it make more sense to place that check even before the `if (blacklisted)` check, if not sooner?

**Comment by codebicycle** [comment]
Thanks for bringing it to attention and for the code contribution.
The fix is once again live.
