### ISSUE TITLE
Fullscreen YouTube is closed in Firefox once VSC loads

### ISSUE THREAD

**Issue by garyking** [codebicycle/videospeed#18]
In Firefox:

1. Open a YouTube video
2. Launch the video in fullscreen before the rest of the page and VSC loads
3. Once VSC loads, the video exits from fullscreen.

Is it possible to NOT exit from fullscreen when VSC loads, if I'm already in fullscreen?

This bug apparently does not occur in the Chrome version of the addon.

**Comment by codebicycle** [comment]
Even with the add-on disabled, on Youtube, quickly pressing F5 and the Full Screen button enters and then exits full screen mode.

I can't observe any different behavior with the extension enabled or with it disabled in Firefox Quantum (57.0.1) on Ubuntu (or in Chromium for that matter).
