### ISSUE TITLE
Firefox 53.0.3 3playmedia rendering is off.

### ISSUE THREAD

**Issue by dwcraig** [codebicycle/videospeed#2]
Watching a video for a class and when played in Chrome with the extension on or with the extension off in Firefox, the video renders properly, but when played with the extension on in the latest version of Firefox, about a third of the video is rendered below the frame of the web player.  Videos render properly in Youtube so seems like something to do with that specific web player.

**Comment by codebicycle** [comment]
Update the extension to the latest version and if it doesn't solve the issue provide me a link to check it out.
