### ISSUE TITLE
[Feature Request] enable whitelisting sites instead of blacklisting

### ISSUE THREAD

**Issue by rxy95** [codebicycle/videospeed#20]
I would like to use this addon on only a couple sites and have it off by default. could you implement an option that inverts the blacklist to a whitelist?

**Comment by codebicycle** [comment]
Hi and thanks for your interest.

This extension is a fork of the `Video Speed Controller` Chrome extension, with minor changes to make it work on Firefox.
It will stay as close as possible to the original https://github.com/igrigorik/videospeed

Any new features should be discussed there, and if implemented they will be available in Firefox too.
