### ISSUE TITLE
[Feature Request] Show controller when changing speed

### ISSUE THREAD

**Issue by jdpurcell** [codebicycle/videospeed#21]
When the controller is hidden, it would be nice if it appeared briefly (1 second or so) when changing the speed.

Like the way it works in mpv, if you've ever seen that:
![speed2](https://user-images.githubusercontent.com/6741660/37071592-330ec0c6-218b-11e8-9e1f-dc43ccf60309.gif)

**Comment by codebicycle** [comment]
Hi and thanks for your interest.

This extension is a fork of the `Video Speed Controller` Chrome extension, with minor changes to make it work on Firefox.
It will stay as close as possible to the original https://github.com/igrigorik/videospeed

Any new features should be discussed there, and if implemented they will be available in Firefox too.
