### ISSUE TITLE
unable to change decrease/increase speed shortcuts to -/=

### ISSUE THREAD

**Issue by sarahwbs** [codebicycle/videospeed#22]
I would like to use the - and = keys to change video speed. When I try to enter these keys in the options form, it simply changes back to the original values. I was able to make this change in the chrome add-on. I am running Firefox 58.0.2 on macOS.

**Comment by codebicycle** [comment]
Thanks for reporting this.

I have pushed a fix to GitHub and if no problems arise it will be available on the next release.
