### ISSUE TITLE
Youtube videos don't start

### ISSUE THREAD

**Issue by BubiBalboa** [codebicycle/videospeed#23]
On Firefox 60.0b5 Youtube videos don't play when Video Speed Controller 0.4.9.4 is enabled.

**Comment by codebicycle** [comment]
I can't replicate this problem on my end on Ubuntu Linux in Firefox 59.0.1 (64-bit), Firefox 60.0b5 (64-bit) or Firefox Nightly 61.0a1 (64-bit).
Could there be any other add-ons interfering?

**Comment by BubiBalboa** [comment]
Possibly? I also run Iridium, UBlock Origin, NoScript and a few userscripts that apply to Youtube specifically.

I turned off Iridium since it modifies Youtube the most but it didn't help, then I turned off Video Speed and everything was fine again even with Iridium reactivated. 

I can play around with it some more to see if I can find another addon that  might cause the problems.

**Comment by BubiBalboa** [comment]
The latest update seems to have fixed my problem.
