### ISSUE TITLE
request for change-log

### ISSUE THREAD

**Issue by atomGit** [codebicycle/videospeed#24]
please consider publishing a change-log, preferably in Firefox when the add-on is updated - i see the 0.5.0 update was released, but how does one know what was changed/added/fixed?

thanks

**Comment by codebicycle** [comment]
That's a good point.

I've added the following release notes for the 0.5.0 update on the [add-on's page](https://addons.mozilla.org/en-US/firefox/addon/videospeed/)
+ Allow minus, equal and semicolon keys to be used as shortcuts.
+ Better way of following mouse on controller drag.
+ Small performance increase.

**Comment by atomGit** [comment]
thank you sir :)
