### ISSUE TITLE
Doesn't Work When Opening Video in New Tab

### ISSUE THREAD

**Issue by pjp2020** [codebicycle/videospeed#25]
I primarily use VSC for YouTube, and it's worked flawlessly until today. Now, when opening a YT video in a new tab, VSC is nowhere to be found. It's not hidden - "V" doesn't display/hide the playback, "S" or "D" have no effect on playback speed. I'd really appreciate this being fixed, as it's a feature I use regularly and love being able to adjust playback speed during my deep YT dives.

**Comment by codebicycle** [comment]
Can you give more details on how to replicate the issue, because it's working fine on my end.
Firefox version and other extensions that might be interfering could provide additional clues.
