### ISSUE TITLE
Pause/Resume feature please

### ISSUE THREAD

**Issue by diyseguy** [codebicycle/videospeed#26]
I love this add-on so much.  It has improved my video experience tremendeously.  I'd like to request keyboard shortcuts for pause and resume.

Thank you

**Comment by codebicycle** [comment]
Thank you!

This extension is a fork of the `Video Speed Controller` Chrome extension, with minor changes to make it work on Firefox.
It will stay as close as possible to the original https://github.com/igrigorik/videospeed

Any new features should be discussed there, and if implemented they will be available in Firefox too.

**Comment by kbumsik** [comment]
@codebicycle Actually, this feature is introduced in upstream: [#399](https://github.com/igrigorik/videospeed/pull/399).

**Comment by codebicycle** [comment]
The current version is up to date with upstream.
Pause/Resume and other custom shortcuts are available in Firefox too.

Exemplification from the post above:
![settings screenshot](https://user-images.githubusercontent.com/5208103/49703812-f1bf5e80-fc1a-11e8-8dd3-7810a65629fb.png)
