### ISSUE TITLE
It does not work anymore as before

### ISSUE THREAD

**Issue by francesco-cadei** [codebicycle/videospeed#27]
I don't know if it's only a my problem but sometimes not start and i have to reload the page to enable the effect.
Firefox ESR 52.7.3 (64-bit).
Thanks

**Comment by codebicycle** [comment]
Does this problem occur on a specific site or is it more general?
Are there other add-ons that might be interfering?
More details on how to replicate this issue would help.

**Comment by francesco-cadei** [comment]
YouTube also Dtube so i think is general..

My Ads-Ons are:
![image](https://user-images.githubusercontent.com/25520099/38580801-398015c2-3d0b-11e8-94dd-c5b00591b8a1.png)

**Comment by codebicycle** [comment]
With the latest release this issue should be fixed.
Thanks for your feedback.

**Comment by francesco-cadei** [comment]
I recently switch to Firefox Quantum 59.0.3 (64-bit) and seem to work perfect.
With Firefox ESR 52.7.3 (64-bit) maybe is not fully compatible.
Thanks
