### ISSUE TITLE
Addon stopped working after update

### ISSUE THREAD

**Issue by jmiskovic** [codebicycle/videospeed#29]
First of all, thank you for creating and maintaining this addon, it's very useful to me.

About a week ago the addon stopped working. In preferences all keys are displayed as un-assigned. If I map keys and press Save button, they are still un-assigned next time I enter preferences. The UI controller doesn't show up on any video page.

I'm running Firefox 59.0.2 (64bit) on LInux Mint and the addon version is 0.5.1. Let me know if I can provide more info to debug this issue.

**Comment by codebicycle** [comment]
I can't replicate it on my end, the versions specified are working on Ubuntu.

Can you reinstall the add-on and see if there is a change.

**Comment by jmiskovic** [comment]
I tried re-installing, got same results. Controls never show up, and shortcuts are always unassigned. How complicated is it to obtain a log to see what went wrong?

**Comment by codebicycle** [comment]
Are there other add-ons that might be interfering?

**Comment by jmiskovic** [comment]
OK, I disabled bunch of other addons and VideoSpeedControl started working. Then I re-enabled them one-by-one and the addon is still working. Weird.

Thanks for the support, I'll close the issue.
