### ISSUE TITLE
Feature Request - Add option for  HTML5 audio element

### ISSUE THREAD

**Issue by george-viaud** [codebicycle/videospeed#3]
I believe this should be a fairly simple thing to add (perhaps just updating the selector pattern) as HTML5 Audio and Video both support the same playbackRate variable if I'm not mistaken.

This is super useful when listening to podcasts online!  Right now I have a custom HTML file I use to playback podcasts locally at high speed which is cumbersome - it would be great if this feature was exposed in all online HTML5 Audio I listen to.

Many thanks!

**Comment by codebicycle** [comment]
Thanks for the suggestion.

This Firefox version is a fork of a Chrome extension.
The Chrome one has more visibility and more developers contributing.
If the feature you are asking for will be implemented there it will be available in Firefox too.

Here are some relevant discussions, that you can contribute to:
https://github.com/igrigorik/videospeed/issues/158
https://github.com/igrigorik/videospeed/issues/122

**Comment by george-viaud** [comment]
Great info - thank you!

**Comment by HackerChick** [comment]
Are there any updates on this, now that the Chrome extension supports Audio? Thanks!

**Comment by codebicycle** [comment]
Closing as the current version supports audio.
