### ISSUE TITLE
Video Speed Settings Lost When Scrolling Down on Youtube

### ISSUE THREAD

**Issue by jake1317** [codebicycle/videospeed#30]
Recently, Youtube started using a mini-player in the top corner of the screen when you scroll down the page during video playback.  When the video switches to this mini-player, the speed settings are lost and need to be adjusted again after scrolling back to the top of the page.

**Comment by ThoughtPhotography** [comment]
Also having issues with the speed settings lost in situations that didn't happen in Chrome (resizing, scrolling, unsuspending etc.)

**Comment by codebicycle** [comment]
The current version is up to date with the Chrome one.
