### ISSUE TITLE
Make this an activeTab extension

### ISSUE THREAD

**Issue by kamalmarhubi** [codebicycle/videospeed#32]
Instead of requiring permissions for all sites, this could work really well as an [activeTab extension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#activeTab_permission). There would be a need to hit a hot key to enable the extension for the tab with video, after that it will work as it does now. This would get rid of any security or privacy concerns someone might have, and additionally improve performance by not injecting the script in every page.

**Comment by kamalmarhubi** [comment]
If you think you'd make a release with that change, I'd be willing to take a crack at the implementation.

**Comment by codebicycle** [comment]
This extension is a fork of the `Video Speed Controller` Chrome extension, with minor changes to make it work on Firefox.
I would like to keep it as close as possible to the original https://github.com/igrigorik/videospeed

**Comment by kamalmarhubi** [comment]
Understood, opening the same issue against upstream.

**Comment by frankclaassens** [comment]
@kamalmarhubi see followup here: https://github.com/igrigorik/videospeed/issues/522
