### ISSUE TITLE
Can't assign pg down to shortcut

### ISSUE THREAD

**Issue by hhijjawi** [codebicycle/videospeed#35]
Certain keys won't work for the video speed shortcuts.

**Comment by codebicycle** [comment]
Hi and thanks for your interest.

This extension is a fork of the `Video Speed Controller` Chrome extension, with minor changes to make it work on Firefox.
It will stay as close as possible to the original https://github.com/igrigorik/videospeed

Any new features should be discussed there, and if implemented they will be available in Firefox too.
