### ISSUE TITLE
control/reset speed with mouse wheel [feature]

### ISSUE THREAD

**Issue by atomGit** [codebicycle/videospeed#39]
would be great to control the video speed with a mouse wheel and reset with middle-click

**Comment by codebicycle** [comment]
Hi and thanks for your interest.

This extension is a fork of the `Video Speed Controller` Chrome extension, with minor changes to make it work on Firefox.
It will stay as close as possible to the original https://github.com/igrigorik/videospeed

Any new features should be discussed there, and if implemented they will be available in Firefox too.
