### ISSUE TITLE
TypeError: can't access dead object inject.js:224:1

### ISSUE THREAD

**Issue by johnp** [codebicycle/videospeed#4]
I see thousands upon thousands of this error in the browser console in Firefox Nightly. [This](https://github.com/codebicycle/videospeed/blob/8b6a54d978639e3868d974298589db0b65ee6b26/inject.js#L224) is the offending line.

There's an MDN page for this specific error and how to deal with it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Dead_object

**Comment by johnp** [comment]
I made a [pull request](https://github.com/igrigorik/videospeed/pull/246) upstream that should also fix this issue (use the readystatechange event instead of constant polling).

**Comment by johnp** [comment]
The fix has been merged upstream and is in release 0.4.9.

**Comment by codebicycle** [comment]
Thank you!
