### ISSUE TITLE
Looking for a way to manipulate speed without producing characters on screen. (such as using keys besides letters, numbers, and punctuation)

### ISSUE THREAD

**Issue by MBTHVSK** [codebicycle/videospeed#40]
Hi there, I discovered this app while on a forum for a certain transcription site.   As of now, being able to reduce the speed to below the allowed 50% (on the website's browser-based system) is very convenient, since some files are just easier to keep up with around 37% or so.  I am entirely capable of using this add-on to change speed as I see fit.

However, one thing I really, really want to do, is to be able to manipulate speed while typing, so I can match the rate of speech to typing, and alter speed as a much less wasteful alternative to pausing.

This is already possible under normal conditions using the browser-based system of the transcription site, since the keyboard shortcuts for that can involve nearly any key on the board, such as CTRL, SHIFT, etc., but you can't go below 50% this way.   I can get a foot pedal set up this way, and it works out pretty nicely, but I want to be able to go below 50% speed.

The video speed add-on (for Firefox or Chrome) seems to require you to set its shortcuts to a letter, number, or punctuation key.  And while it's possible to use these shortcuts to manipulate the speed in the normally allowed above-50%-range, trying to get slower than that seems to require the use of those add-on-based shortcuts.

Basically, what I'm saying is, as of now, if I want to type while manipulating speed below 50%, it's only possible to use character-generating keys.  Therefore, characters will appear on the screen, which completely interferes with the transcription.

As of now, I'm being forced to click away from the "type here" field, press those shortcut characters, and then go back to the "type here" field. But I don't want to do that.  I just want to be able to change the speed with a foot pedal like I have been, but this time, being able to go below 50% speed for it.

So, what I need is, some kind of option that lets you set the speed-changing shortcuts to control, option, command, F1, F5, etc.   There might be some other solution, but since I know nothing about computers compared to the people here, I really can't suggest anything else.

Just to recap: I'm trying to gain the ability to change a video's speed, using this add-on, while within a "typing field", without producing any characters in a typing field.

I guarantee you many people will appreciate the efforts in providing a solution for this problem in the extension you have here.

I also apologize if my lack of knowledge about anything to do with coding makes this post inappropriate.   On the website's forum, I was recommended to come here and leave feedback.  Thanks to you all.

**Comment by serenity777** [comment]
Video

**Comment by codebicycle** [comment]
Hi and thanks for your interesting use case.

This extension is a fork of the `Video Speed Controller` Chrome extension, with minor changes to make it work on Firefox.
It will stay as close as possible to the original https://github.com/igrigorik/videospeed

Any new features should be discussed there, and if implemented they will be available in Firefox too.
