### ISSUE TITLE
Firefox for Linux won't play two videos at once

### ISSUE THREAD

**Issue by ghost** [codebicycle/videospeed#41]
When browsing, I often play two videos simultaneously, keeping one or both in the background so I have just the audio. (YouTube has a lot of podcasts and a lot of music, for example, so I'll play a podcast on one tab with some background music on another and then do something else with my time.) However, when the add-on is enabled, I can no longer do that: playing one video automatically pauses the other.

This is mildly annoying.

**Steps to reproduce:**

1. Start Firefox.
2. Open two tabs on YouTube (just as an example); select two videos.
3. Play one.
4. Switch tabs; play the other.

**What should happen:**

The videos play with overlapping audio.

**What happens:**

The video just selected plays, but the video in the non-selected tab is paused.

**Platform information:**

I'm using Firefox 63.0.1 on the KDE Spin of Fedora 29.

**Comment by codebicycle** [comment]
I could not reproduce this on Firefox 63.0 running on Ubuntu.
The audio plays fine from multiple tabs at the same time.

Try to disable other add-ons that might be interfering and see if the issue persists.

**Comment by ghost** [comment]
Nevermind, the problem persists when I turn off the add-on. (Though only some of the time, which is why I thought it was the add-on's fault.)

Oops.
