### ISSUE TITLE
[UX Discovery] Autohide Controller

### ISSUE THREAD

**Issue by Riajyuu** [codebicycle/videospeed#46]
Now the speed number is always displayed and seems weird.
Here is what I suggest:
1. upon page loading, show a persistent number.
1. after page loading done (or perhaps player loading done), hide the number after a timeout. 3~5s is proper, I guess.
1. recall the number when users move the curse back to player's top-left area.

This is UX elegant enough so I don't think an option necessary.

Note that current speed number is a bit hard to discover in some case. You can add some blinks to avoid users missing it before it is being hidden.

**Comment by codebicycle** [comment]
Hi and thanks for your interest,

The `V` keyboard shortcut shows/hides the controller. Changing speeds via the keyboard will make it briefly visible again.
There is also a `Hide controller by default` checkbox in settings.
