### ISSUE TITLE
Doesn't work if click Event + window.open is blocked

### ISSUE THREAD

**Issue by pintassilgo** [codebicycle/videospeed#5]
about:config
`dom.popup_allowed_events`

This pref allows to block events from spawning popups. including `click`, used by this extension to open settings tab. I and others block all popups by leaving this entry empty. But this way we can't open Video Speed Controller settings.

I don't have this problem with other WebExtensions that open a tab with their settings by clicking a button item, for example [Checker Plus For Gmail](https://addons.mozilla.org/en-US/firefox/addon/checker-plus-gmail/).

Maybe should replace `window.open` (popup) by the suitable [chrome.tabs.create](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create)?

**Comment by codebicycle** [comment]
Now you can access the settings with the `Preferences` button on the `Add-ons` view (`about:addons`).

**Comment by ghost** [comment]
thank you :)
