### ISSUE TITLE
Bing search not accepting enter

### ISSUE THREAD

**Issue by BoomRaccoon** [codebicycle/videospeed#51]
I have the issue that bing won't accept the enter key. I deactivated the add-on and bing accepts enter to start the search again.

**Comment by ghost** [comment]
Same issue. I just put bing on the blacklist.

**Comment by BoomRaccoon** [comment]
Oh my, totally ignored the fact that I can put a site without video content on the blacklist.
Thank you very much.

**Comment by mastahype** [comment]
I'd like to re-open this. Blacklisting Bing.com isn't the solution because bing also has a video search option with embedded youtube videos. Those videos don't get the videospeed overlay because it's blacklisted on the domain.
