### ISSUE TITLE
Missing some settings from Chrome version

### ISSUE THREAD

**Issue by HackerChick** [codebicycle/videospeed#56]
Is there any way to port the additional features from the Chrome extension to the Firefox one? 

Specifically:
- Shortcuts "Add New" button. Allows you add additional hotkeys. For example, in Chrome I have multiple hot keys for different "Preferred Speed" settings (1.5, 2.0, etc)

- Experimental Feature: Disable websites key binding. Otherwise, if you use customized shortcut keys they can conflict with YouTube settings

- Work on Audio (including for completeness sake, although I know this is also in Issue #3)

**Comment by codebicycle** [comment]
The Firefox version is now up to date with the upstream Chrome version.
