### ISSUE TITLE
Not working on firefox

### ISSUE THREAD

**Issue by konarkuomaten** [codebicycle/videospeed#63]
Firefox and add-on are both up to date. The controller is not showing up on a video. Attempting to change the settings (accessed by clicking on the app icon) does nothing.

**Comment by abg88** [comment]
Next week, the FX extension will not be updated for a year. I think the dev gave up the FX extension.

**Comment by kult** [comment]
Same problem. Firefox 71 for OSX 10.15.2. I love this extension, so I hope it works again someday!

**Comment by codebicycle** [comment]
The current version is up to date with the Chrome one.
