### ISSUE TITLE
[Feature Request] Ability to change color and opacity of overlay

### ISSUE THREAD

**Issue by torifaye** [codebicycle/videospeed#75]
Hi, I love the extension, but sometimes the overlay isn't visible due to the contents of the video - is there any chance there could be a setting added to modify the default color and/or opacity of it?

**Comment by codebicycle** [comment]
Hi,
In the new version, you can control the opacity from the settings.
Look for `Controller opacity`. It can take values from 0.0 to 1.0.
The lower the value, the more transparent.

**Comment by torifaye** [comment]
@codebicycle I see, thanks for adding the feature!
