### ISSUE TITLE
No longer able to use "-" and "=" or "+" as keyboard controls

### ISSUE THREAD

**Issue by anon2828226** [codebicycle/videospeed#76]
Until today I used "-" as a shortcut for "decrease speed" and "=" or "+" for "increase speed". these keyboard controls, shortcuts stopped working.
Now when I try to set those as shortcut in the settings and save it resets to the defaults. experimentally if I do "add new" and try and enter any of these desired keyboard shortcuts and save when I reload the setting page it says "null" as the shortcut.  feel free to message me for more details or clarifications.

**Comment by codebicycle** [comment]
I will fix this over the weekend.

**Comment by nelooangeloo** [comment]
semicolon key can't be assigned as well.
; 
it will switch back to last legal key (a s d f, etc) when you refresh the page

**Comment by codebicycle** [comment]
These keys are once again available in version 0.5.9.1.
Thanks for the prompt feedback.
