### ISSUE TITLE
Update to 0.5.9 in Firefox seems to have reset keyboard shortcuts

### ISSUE THREAD

**Issue by Jonta** [codebicycle/videospeed#81]

**Comment by codebicycle** [comment]
Version 0.5.9 comes with many improvements and with some drawbacks also.
Version 0.5.9.1 is also released and updating from 0.5.9 to the newer version will remember the keyboard shortcuts.

**Comment by Jonta** [comment]
0.5.9.1

They were just reset to defaults again
