### ISSUE TITLE
do not mute audio

### ISSUE THREAD

**Issue by hhielscher** [codebicycle/videospeed#83]
If I increase the speed above 4x the sound will be muted. Please add an option to enable audio above 4x speed. (This is useful when I want to skip music and want to go to the next spoken part or vice versa.)

I use Firefox 75.

**Comment by codebicycle** [comment]
Hi, the 4x limitation comes from Firefox.

**Comment by sirati** [comment]
is there a way to disable that limitation? like maybe a firefox config entry?

**Comment by sirati** [comment]
i filed a bug with firefox
https://bugzilla.mozilla.org/show_bug.cgi?id=1630569

**Comment by braham-snyder** [comment]
To anyone reading: if this affects you, you might want to vote on that bug @sirati filed. You can vote using your GitHub account.
