### ISSUE TITLE
Unreal docs are broken with this addon

### ISSUE THREAD

**Issue by GonziHere** [codebicycle/videospeed#84]
Hi, I see this: 
![image](https://user-images.githubusercontent.com/8655073/79136752-d38ae500-7db1-11ea-8abd-5bbc5a6bb07d.png)
when I use this addon, but when I disable it, it works as it should:
![image](https://user-images.githubusercontent.com/8655073/79137081-5875fe80-7db2-11ea-87c3-805a5e1654b9.png)
I was able to reproduce this issue with everything else disabled and just enabling/disabling this addon, but it doesn't always happen. 

website to test:
https://docs.unrealengine.com/en-US/API/Runtime/Core/Containers/TArray/Num/index.html

BTW I use this addon religiously, with every video everywhere, so thank you very much for making it.

**Comment by codebicycle** [comment]
Thanks for taking the time to investigate.
Version 0.6.1 was released and should address this issue.
