### ISSUE TITLE
Audio turns off at speed higher 4x

### ISSUE THREAD

**Issue by sirati** [codebicycle/videospeed#85]
Hallo,
that might sound weird but I watch videos at a very very high speed, lately between 3.3 and 3.8x, today I wanted for the first time to go beyond 4x times but realised that the audio stops completely if a speed higher than 4x is selected.

**Comment by sirati** [comment]
duplicate of #83

**Comment by braham-snyder** [comment]
To anyone subbed: if this affects you, you might want to vote on this [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1630569) @sirati filed. You can vote using your GitHub account.
