### ISSUE TITLE
Feature request : select video quality

### ISSUE THREAD

**Issue by ghost** [codebicycle/videospeed#87]
I would like to know if it's possible to add a button to select the quality of the video or define a selected quality? My purpose is to select a less effective quality in order to limit the impact of digital from ecological point of view. 

I know that your program is done for selecting the speed but I think that could be a good improvement.
I didn't find any plugin able to do that on mozilla...
Thank for reading

**Comment by codebicycle** [comment]
Thanks for the suggestion.
Unfortunately, this feature is not in the scope of this extension.

Maybe someone else will implement such an add-on.
