### ISSUE TITLE
Controller is not top-most

### ISSUE THREAD

**Issue by Synetech** [codebicycle/videospeed#9]
It would be better if instead of having the controller be inside the `html5-video-container`, have it be its sibling (figure 2). That way, the controller can be placed on top of YouTube's normal interface, and thus be less obtrusive (not in the video itself), as seen in the attached screenshot (figure 1). I'm new to Firefox extensions, but I believe it should be as simple as changing line `195` of `inject.js` from

> this.parent.insertBefore(fragment, this.parent.firstChild);

to

> this.parent.insertBefore(fragment, this.parent.parent.firstChild);

<br />

**figure 1**
![screenshot-2017-09-15--21-37-30 - 02_08 _ 06_22 - scishow the quantum internet of the future i-w3d_nr4_e - youtube](https://user-images.githubusercontent.com/5210197/30508182-d2965d2a-9a5e-11e7-8c29-e49e5f39fb8e.png)

**figure 2**
![screenshot-2017-09-15--21-38-10 - developer tools - 01_40 _ 06_22 - scishow the quantum internet of the future i-w3d_nr4_e - youtube - https___www youtube com_embed_videoseries_list plee4zqavzhiri6tiivelfdig36wghdnqe](https://user-images.githubusercontent.com/5210197/30508181-d2739a74-9a5e-11e7-91ef-38898c74e474.png)

**Comment by Synetech** [comment]
Also, it would be great if you could make it prevent videos from auto-playing as well.

**Comment by codebicycle** [comment]
Hi and thanks for your interest.

This extension is a fork of the `Video Speed Controller` Chrome extension, with minor changes to make it work on Firefox.
It will stay as close as possible to the original https://github.com/igrigorik/videospeed

Any new features should be discussed there, and if implemented they will be available in Firefox too.
