### ISSUE TITLE
Prevents PayPal Checkout page from proceeding

### ISSUE THREAD

**Issue by stephenkoo** [codebicycle/videospeed#92]
(Firstly, I love your addon, thanks.)

I have to disable the Firefox extension whenever I make a payment through checkout because the PayPal checkout redirect screen just stays with the spinner/loading icon without opening the PayPal pop-up window to select a payment method.

I've isolated the cause to this addon as it enabling/disabling it determines whether PayPal checkout is successful or not.

**Comment by codebicycle** [comment]
Thanks for taking the time to investigate.
Version 0.6.1 was just released.

Can you please verify if the issue persists.

**Comment by stephenkoo** [comment]
Yes, unfortunately 0.6.1 does not solve the issue:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/18624246/81559570-02a56e00-93d3-11ea-8146-599ea15dd5a1.png">

**Comment by stephenkoo** [comment]
Perhaps a solution would be to blacklist certain sites so the addon doesn't run on them?

**Comment by codebicycle** [comment]
The possibility to blacklist sites is already available from the extension settings page.

**Comment by stephenkoo** [comment]
Ah, I see it. I'll add `paypal.com` to the blacklist. I can close this issue and re-open it if the problem persists.
Thanks @codebicycle.
