### ISSUE TITLE
Firefox goes to full screen when clicked

### ISSUE THREAD

**Issue by mzayani** [codebicycle/videospeed#98]
whenever i try to change the speed Firefox goes to full screen. click again and window restored to normal.
basically all buttons just switch full screen mode. Firefox 77.0.1 MacOS

**Comment by xdhmoore** [comment]
This happens to me on Windows on Vimeo videos as well. I am guessing a click handler just needs a "prevent default" call somewhere.

**Comment by xdhmoore** [comment]
It looks like this has been fixed upstream hasn't made it to this repo yet? https://github.com/igrigorik/videospeed/pull/635

**Comment by xdhmoore** [comment]
Hurray! Works for me now! 🎈 Thank you!
